<?php
/**
 * CategorySaveObserver.php
 *
 * @package OlegKoval_RegenerateUrlRewrites
 * @author Oleg Koval <olegkoval.ca@gmail.com>
 * @copyright 2017-2067 Oleg Koval
 * @license OSL-3.0, AFL-3.0
 */

namespace OlegKoval\RegenerateUrlRewrites\Observer;

use Magento\Framework\Event\Observer;
use Magento\Framework\Event\ObserverInterface;
use OlegKoval\RegenerateUrlRewrites\Helper\Regenerate as RegenerateHelper;

class CategorySaveObserver implements ObserverInterface
{
    /**
     * @var RegenerateHelper
     */
    private RegenerateHelper $helper;

    /**
     * @param RegenerateHelper $helper
     */
    public function __construct(RegenerateHelper $helper)
    {
        $this->helper = $helper;
    }

    /**
     * Ensure the category url_key uses correct German umlaut transliteration.
     * Same logic as ProductSaveObserver — see that class for the detailed explanation.
     *
     * @param Observer $observer
     * @return void
     */
    public function execute(Observer $observer): void
    {
        /** @var \Magento\Catalog\Model\Category $category */
        $category = $observer->getEvent()->getCategory();

        if (!$category) {
            return;
        }

        $name = (string)$category->getName();
        if ($name === '') {
            return;
        }

        $transliteratedName = $this->helper->transliterateGermanCharacters($name);
        $urlKey = (string)$category->getUrlKey();

        if ($transliteratedName === $name) {
            // Name has no German umlauts — only fix if the key itself has some
            if ($urlKey !== '') {
                $transliteratedKey = $this->helper->transliterateGermanCharacters($urlKey);
                if ($transliteratedKey !== $urlKey) {
                    $category->setUrlKey($this->helper->formatUrlKey($transliteratedKey));
                }
            }
            return;
        }

        // Name contains German umlauts → determine the correct key
        $correctKey = $this->helper->formatUrlKey($transliteratedName);

        // Override only when the key is absent or was auto-filled by JS (wrong)
        if ($urlKey === '' || $this->helper->isLikelyAutoGeneratedUrlKey($urlKey, $name)) {
            $category->setUrlKey($correctKey);
        }
    }
}
