<?php
/**
 * ProductSaveObserver.php
 *
 * @package OlegKoval_RegenerateUrlRewrites
 * @author Oleg Koval <olegkoval.ca@gmail.com>
 * @copyright 2017-2067 Oleg Koval
 * @license OSL-3.0, AFL-3.0
 */

namespace OlegKoval\RegenerateUrlRewrites\Observer;

use Magento\Framework\Event\Observer;
use Magento\Framework\Event\ObserverInterface;
use OlegKoval\RegenerateUrlRewrites\Helper\Regenerate as RegenerateHelper;

class ProductSaveObserver implements ObserverInterface
{
    /**
     * @var RegenerateHelper
     */
    private RegenerateHelper $helper;

    /**
     * @param RegenerateHelper $helper
     */
    public function __construct(RegenerateHelper $helper)
    {
        $this->helper = $helper;
    }

    /**
     * Ensure the product url_key uses correct German umlaut transliteration.
     *
     * Problem: Magento's admin JS auto-fills the URL-Key field as the user types
     * the name, but maps ä→a, ö→o, ü→u (single Latin chars) instead of the
     * correct German equivalents ä→ae, ö→oe, ü→ue.  By the time this observer
     * runs, the field already contains the wrong value, which is not empty and
     * contains no umlauts — so the naïve "fix umlauts in url_key" guard misses it.
     *
     * Fix strategy:
     *   1. If the name has no German umlauts → only correct the key if it
     *      contains umlauts itself (e.g. manually entered).
     *   2. If the name HAS umlauts → build the correct key from the name.
     *      Apply it when the current key is empty OR matches the wrongly
     *      auto-generated JS candidate.  A key that is neither empty nor the
     *      JS candidate was set deliberately and is left untouched.
     *
     * @param Observer $observer
     * @return void
     */
    public function execute(Observer $observer): void
    {
        /** @var \Magento\Catalog\Model\Product $product */
        // catalog_product_save_before passes the product as both 'product' and 'object'
        $product = $observer->getEvent()->getProduct() ?? $observer->getEvent()->getObject();

        if (!$product) {
            return;
        }

        $name = (string)$product->getName();
        if ($name === '') {
            return;
        }

        $transliteratedName = $this->helper->transliterateGermanCharacters($name);
        $urlKey = (string)$product->getUrlKey();

        if ($transliteratedName === $name) {
            // Name has no German umlauts — only fix if the key itself has some
            if ($urlKey !== '') {
                $transliteratedKey = $this->helper->transliterateGermanCharacters($urlKey);
                if ($transliteratedKey !== $urlKey) {
                    $product->setUrlKey($this->helper->formatUrlKey($transliteratedKey));
                }
            }
            return;
        }

        // Name contains German umlauts → determine the correct key
        $correctKey = $this->helper->formatUrlKey($transliteratedName);

        // Override only when the key is absent or matches the JS auto-generated
        // candidate (ä→a, ö→o, ü→u). A key with a duplicate-suffix like "-1"
        // (set by Magento during product duplication) does not match the JS
        // pattern and is left untouched.
        if ($urlKey === '' || $this->helper->isLikelyAutoGeneratedUrlKey($urlKey, $name)) {
            $product->setUrlKey($correctKey);
        }
    }
}
