<?php
/**
 * Regenerate.php
 *
 * @package OlegKoval_RegenerateUrlRewrites
 * @author Oleg Koval <olegkoval.ca@gmail.com>
 * @copyright 2017-2067 Oleg Koval
 * @license OSL-3.0, AFL-3.0
 */

namespace OlegKoval\RegenerateUrlRewrites\Helper;

use Magento\Framework\App\Helper\AbstractHelper;
use Magento\Framework\App\Helper\Context;
use Magento\Store\Model\StoreManagerInterface;
use Magento\Framework\App\Config\ScopeConfigInterface;

class Regenerate extends AbstractHelper
{
    /**
     * @var StoreManagerInterface
     */
    protected $storeManager;

    /**
     * @var ScopeConfigInterface
     */
    protected $scopeConfig;

    /**
     * Regenerate constructor.
     * @param Context $context
     * @param StoreManagerInterface $storeManager
     */
    public function __construct(
        Context               $context,
        StoreManagerInterface $storeManager
    )
    {
        parent::__construct($context);
        $this->storeManager = $storeManager;
        $this->scopeConfig = $context->getScopeConfig();
    }

    /**
     * Get store manager
     *
     * @return StoreManagerInterface
     */
    public function getStoreManager(): StoreManagerInterface
    {
        return $this->storeManager;
    }

    /**
     * Get config value of "Use Categories Path for Product URLs" config option
     *
     * @param int|null $storeId
     * @return boolean
     */
    public function useCategoriesPathForProductUrls(?int $storeId = null): bool
    {
        return (bool)$this->scopeConfig->getValue(
            'catalog/seo/product_use_categories',
            \Magento\Store\Model\ScopeInterface::SCOPE_STORES,
            $storeId
        );
    }

    /**
     * Sanitize product URL rewrites
     *
     * @param array $productUrlRewrites
     * @return array
     */
    public function sanitizeProductUrlRewrites(array $productUrlRewrites): array
    {
        $paths = [];
        foreach ($productUrlRewrites as $key => $urlRewrite) {
            $path = $this->_clearRequestPath($urlRewrite->getRequestPath());
            if (!in_array($path, $paths)) {
                $productUrlRewrites[$key]->setRequestPath($path);
                $paths[] = $path;
            } else {
                unset($productUrlRewrites[$key]);
            }
        }

        return $productUrlRewrites;
    }

    /**
     * Clear request path
     * @param string $requestPath
     * @return string
     */
    protected function _clearRequestPath(string $requestPath): string
    {
        return str_replace(['//', './'], ['/', '/'], ltrim(ltrim($requestPath, '/'), '.'));
    }

    /**
     * Transliterate German characters (umlauts) to their ASCII equivalents
     *
     * @param string $string
     * @return string
     */
    public function transliterateGermanCharacters(string $string): string
    {
        $germanCharMap = [
            'ä' => 'ae', 'ö' => 'oe', 'ü' => 'ue', 'ß' => 'ss',
            'Ä' => 'ae', 'Ö' => 'oe', 'Ü' => 'ue',
        ];

        return str_replace(array_keys($germanCharMap), array_values($germanCharMap), $string);
    }

    /**
     * Convert a string to a valid URL key segment.
     * Shared by observers so the formatting logic lives in one place.
     *
     * @param string $value
     * @return string
     */
    public function formatUrlKey(string $value): string
    {
        $value = strtolower(trim($value));
        $value = (string)preg_replace('/[^a-z0-9]+/', '-', $value);
        return trim($value, '-');
    }

    /**
     * Check whether a url_key was auto-generated by Magento's admin JavaScript
     * using incorrect umlaut transliteration (ä→a, ö→o, ü→u) rather than the
     * correct German equivalents (ä→ae, ö→oe, ü→ue).
     *
     * Magento's JS fills the URL-Key field as the user types the name.
     * When the name contains umlauts the JS-generated key is wrong and must be
     * overwritten — but only if the user has not set a deliberate custom key.
     * Comparing the current key against the JS-generated candidate lets us tell
     * auto-fill from a real manual entry.
     *
     * @param string $urlKey   the current value of the url_key field
     * @param string $name     the product/category name
     * @return bool
     */
    public function isLikelyAutoGeneratedUrlKey(string $urlKey, string $name): bool
    {
        // Map that simulates what Magento's admin JS does: single-char replacements
        $jsWrongMap = [
            'ä' => 'a', 'ö' => 'o', 'ü' => 'u', 'ß' => 'ss',
            'Ä' => 'a', 'Ö' => 'o', 'Ü' => 'u',
        ];
        $wrongName = str_replace(array_keys($jsWrongMap), array_values($jsWrongMap), $name);

        return $urlKey === $this->formatUrlKey($wrongName);
    }
}
